In [1]:
import pandas as pd
from tqdm import tqdm
import numpy as np
import os

In [2]:
def id_sort(data):
    data['SortKey'] = data.iloc[:, 0].str.extract(r'(\d+)').astype(int)  # 提取數字部分，轉換為數值型
    data_sorted = data.sort_values(by='SortKey').reset_index(drop=True)  # 按數字部分排序
    data_sorted = data_sorted.drop(columns=['SortKey'])  # 刪除輔助列

    return data_sorted

In [3]:
imputed_data_path = r"V:\dunwei\MACE\dataset\reversed/"
raw_data_path = r"V:\dunwei\MACE\dataset\pre_process/"
signal_data_path = r"V:\dunwei\MACE\dataset\multirocket_result\multirocket\resample_0\MultiRocket_50000\sr2500_500_1000_logistic_51_41\combine/"
save_data_path = r"V:\dunwei\MACE\dataset\pre_process\LR_combine_eight_feature_NA2/"

In [4]:
if not os.path.exists(save_data_path):
    os.makedirs(save_data_path)
    print(f'create directory: {save_data_path}')
else:
    print(f'{save_data_path} already exists')

V:\dunwei\MACE\dataset\pre_process\LR_combine_eight_feature_NA2/ already exists

In [5]:
conversion_id = ['Transformation_ID']
probability = ['prob']
label = ['mace']
feature = ['count_v_ar', 'count_copd', 'smoke_try', 'count_dm', 'male', 'NA2s', 'NA2r', 'NA2b'] # 看要幾個feature

In [6]:
imputed_data = pd.read_csv(imputed_data_path + "MACE_imputed_data.csv")
raw_data = pd.read_csv(raw_data_path + "MACE_raw_data.csv")
test_prob = pd.read_csv(signal_data_path + "test_prob.csv").values
display(imputed_data)
display(raw_data)

,Transformation_ID,acei_use,arb_use,c1_use,c3_use,alpha_use,coag_use,plt_use,NSTEMI,STEMI,...,HR_1,count_HF,NA1b,NA2b,NA1s,NA2s,NA1r,NA2r,TIMI,mace
0,MACE001,0,0,0,0,0,0,0,0.0,1,...,99.0,0.0,0.945758,1.914487,1.023857,1.788330,0.818643,1.359674,5.0,0
1,MACE002,1,0,0,0,0,0,1,1.0,0,...,72.0,0.0,0.866184,0.841020,1.057619,0.969397,1.085651,0.900024,4.0,0
2,MACE004,0,0,0,0,0,0,1,1.0,0,...,86.0,0.0,0.800577,1.162385,1.252417,2.451672,0.971383,2.074904,3.0,0
3,MACE005,0,0,0,0,0,0,0,0.0,1,...,64.0,0.0,0.915233,1.028591,1.204876,1.537874,1.025937,0.843889,4.0,0
4,MACE006,0,1,0,0,0,0,0,0.0,1,...,53.0,0.0,0.795437,0.558267,1.008234,0.837322,0.835240,0.643852,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,MACE520,0,1,0,0,0,0,0,0.0,1,...,71.0,0.0,1.105353,1.298373,1.240736,1.829597,0.868486,-2.049724,2.0,0
520,MACE521,0,0,0,0,0,0,0,0.0,1,...,89.0,0.0,1.145215,1.000806,1.142710,1.369862,1.178137,6.936992,4.0,0
521,MACE522,0,0,0,0,0,0,0,0.0,1,...,74.0,0.0,1.389193,2.526931,1.387462,3.051082,1.496427,1.932465,7.0,0
522,MACE523,0,1,0,0,0,0,0,0.0,1,...,77.0,0.0,1.771780,4.081044,1.710707,4.640349,1.360609,1.047252,5.0,0
523,MACE524,0,0,0,0,0,0,0,0.0,1,...,68.0,0.0,1.472067,1.363042,1.133876,1.690293,1.001688,7.173253,3.0,0

,Transformation_ID,acei_use,arb_use,c1_use,c3_use,alpha_use,coag_use,plt_use,NSTEMI,STEMI,...,HR_1,count_HF,NA1b,NA2b,NA1s,NA2s,NA1r,NA2r,TIMI,mace
0,MACE001,0,0,0,0,0,0,0,0.0,1,...,99.0,0.0,0.945758,1.914487,1.023857,1.788330,0.818643,1.359674,5.0,0
1,MACE002,1,0,0,0,0,0,1,1.0,0,...,72.0,0.0,0.866184,0.841020,1.057619,0.969397,1.085651,0.900024,4.0,0
2,MACE003,0,0,0,0,0,0,0,1.0,0,...,80.0,0.0,NaN,0.787275,NaN,NaN,NaN,NaN,4.0,0
3,MACE004,0,0,0,0,0,0,1,1.0,0,...,86.0,0.0,0.800577,1.162385,1.252417,2.451672,0.971383,2.074904,3.0,0
4,MACE005,0,0,0,0,0,0,0,0.0,1,...,64.0,0.0,0.915233,1.028591,1.204876,1.537874,1.025937,0.843889,4.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,MACE520,0,1,0,0,0,0,0,0.0,1,...,71.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0
520,MACE521,0,0,0,0,0,0,0,0.0,1,...,89.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,0
521,MACE522,0,0,0,0,0,0,0,0.0,1,...,74.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,7.0,0
522,MACE523,0,1,0,0,0,0,0,0.0,1,...,77.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0,0
523,MACE524,0,0,0,0,0,0,0,0.0,1,...,68.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [50]:
mode = 1
'''
mode =1 for missing value
mode =2 for non-missing value(used MIDA)
'''
if mode == 1:
    raw_data = raw_data[conversion_id + feature + label]
    raw_data = id_sort(raw_data)
elif mode == 2:
    imputed_data = imputed_data[conversion_id + feature + label]
    imputed_data = id_sort(imputed_data)

display(raw_data)

,Transformation_ID,count_v_ar,count_copd,smoke_try,count_dm,male,NA2s,NA2r,NA2b,mace
0,MACE001,0.0,0.0,1.0,0.0,1,1.788330,1.359674,1.914487,0
1,MACE002,0.0,0.0,1.0,1.0,1,0.969397,0.900024,0.841020,0
2,MACE003,0.0,0.0,0.0,0.0,0,NaN,NaN,0.787275,0
3,MACE004,0.0,0.0,0.0,0.0,1,2.451672,2.074904,1.162385,0
4,MACE005,0.0,0.0,1.0,0.0,1,1.537874,0.843889,1.028591,0
...,...,...,...,...,...,...,...,...,...,...
519,MACE520,0.0,0.0,1.0,0.0,1,NaN,NaN,NaN,0
520,MACE521,0.0,0.0,0.0,0.0,1,NaN,NaN,NaN,0
521,MACE522,0.0,0.0,1.0,1.0,1,NaN,NaN,NaN,0
522,MACE523,0.0,0.0,0.0,1.0,1,NaN,NaN,NaN,0
523,MACE524,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,0

In [51]:
prob_df = pd.DataFrame(test_prob, columns=["ID", "prob"])
prob_sorted = id_sort(prob_df)

In [52]:
prob_count = prob_sorted.iloc[:, 0].value_counts().reset_index()
prob_count.columns = ['ID', 'count']
prob_count_sorted = id_sort(prob_count)
display(prob_count_sorted)

          ID  count
0    MACE001    141
1    MACE002    141
2    MACE003    141
3    MACE004    141
4    MACE005    141
..       ...    ...
516  MACE520    141
517  MACE521    141
518  MACE522    141
519  MACE523    141
520  MACE524    141

[521 rows x 2 columns]

In [53]:
combine = pd.DataFrame()
if mode == 1:
    for i in tqdm(range(len(prob_count_sorted))):
        match_row = raw_data[raw_data.iloc[:, 0] == prob_count_sorted.iloc[i, 0]]
        match_row_duplicate = pd.concat([match_row] * prob_count_sorted.iloc[i, 1], axis=0, ignore_index=True)
        combine = pd.concat([combine, match_row_duplicate], axis=0, ignore_index=True)
elif mode == 2:
    for i in tqdm(range(len(prob_count_sorted))):
        match_row = imputed_data[imputed_data.iloc[:, 0] == prob_count_sorted.iloc[i, 0]]
        match_row_duplicate = pd.concat([match_row] * prob_count_sorted.iloc[i, 1], axis=0, ignore_index=True)
        combine = pd.concat([combine, match_row_duplicate], axis=0, ignore_index=True)

100%|██████████| 521/521 [00:04<00:00, 123.53it/s]

In [54]:
new_tabular_data = pd.concat([combine, prob_sorted.iloc[:, 1]], axis=1)
new_tabular_data = new_tabular_data[conversion_id + feature + probability + label]
if mode == 1:
    new_tabular_data.to_csv(save_data_path + "test_prob_combine_tabular_data_NA1_missing_value.csv", index=False)
elif mode == 2:
    new_tabular_data.to_csv(save_data_path + "test_prob_combine_tabular_data_NA1_non_missing_value.csv", index=False)

print(f"save path : {save_data_path}")

save path : V:\dunwei\MACE\dataset\pre_process\LR_combine_eight_feature_NA2/