In [43]:
import pandas as pd
import os

In [ ]:
raw_data_path = r"F:\M143020071\raw_data/"
save_data_path = r"D:\M143020071\raw_data_result\tabular_data/"
raw_data = pd.read_csv(os.path.join(raw_data_path, "MACE 資料登錄(新增VT)_killip finial.csv"))
display(raw_data)
print("success")

,研究編號,indate_skna,ID,SEX,outdate_skna,INDEXDATE,acei_use,arb_use,c1_use,c3_use,...,master,PCIdate,SKNAdate1,mace_date2,TIMI,Killip,APACH II,ReMI,arrhythmia,p.s
0,414490914181,2016/12/12,13359.0,M,2016/12/16,2016/12/16,0,0,0,0,...,1.0,2016/12/12,2016/12/13,.,5.0,II,NaN,NaN,NaN,NaN
1,534491345995,2016/12/21,20198.0,M,2016/12/29,2016/12/29,1,0,0,0,...,1.0,2016/12/21,2016/12/22,.,4.0,III,NaN,NaN,NaN,NaN
2,584487583289,2019/11/18,11797.0,F,2019/11/25,2019/11/25,0,0,0,0,...,1.0,2019/11/21,2019/11/21,.,4.0,I,NaN,NaN,NaN,NaN
3,354480714133,2017/9/16,12755.0,M,2017/9/21,2017/9/21,0,0,0,0,...,1.0,2017/9/18,2017/9/18,.,3.0,I,NaN,NaN,NaN,NaN
4,364481044155,2017/10/5,44.0,M,2017/10/10,2017/10/10,0,0,0,0,...,1.0,2017/10/5,2017/10/6,.,4.0,I,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,334472223207,2023/2/27,NaN,M,2023/3/3,NaN,0,1,0,0,...,NaN,2023/2/26,2023/3/1,NaN,2.0,I,NaN,0.0,0.0,NaN
520,474468168901,2023/3/1,NaN,M,2023/3/6,NaN,0,0,0,0,...,NaN,2023/3/1,2023/3/2,NaN,4.0,I,NaN,0.0,0.0,NaN
521,484552428693,2023/2/21,NaN,M,2023/2/27,NaN,0,0,0,0,...,NaN,2023/2/21,2023/2/22,NaN,7.0,II,NaN,0.0,1.0,NaN
522,454552424829,2023/2/28,NaN,M,2023/3/7,NaN,0,1,0,0,...,NaN,2023/2/28,2023/3/2,NaN,5.0,I,NaN,0.0,1.0,NaN
523,374552404823,2023/3/7,NaN,F,2023/3/13,NaN,0,0,0,0,...,NaN,2023/3/7,2023/3/9,NaN,NaN,I,3.0,0.0,0.0,NaN

success

In [45]:
non_research_id = raw_data.iloc[:, 1:]
display(non_research_id)
print("success")

,indate_skna,ID,SEX,outdate_skna,INDEXDATE,acei_use,arb_use,c1_use,c3_use,alpha_use,...,master,PCIdate,SKNAdate1,mace_date2,TIMI,Killip,APACH II,ReMI,arrhythmia,p.s
0,2016/12/12,13359.0,M,2016/12/16,2016/12/16,0,0,0,0,0,...,1.0,2016/12/12,2016/12/13,.,5.0,II,NaN,NaN,NaN,NaN
1,2016/12/21,20198.0,M,2016/12/29,2016/12/29,1,0,0,0,0,...,1.0,2016/12/21,2016/12/22,.,4.0,III,NaN,NaN,NaN,NaN
2,2019/11/18,11797.0,F,2019/11/25,2019/11/25,0,0,0,0,0,...,1.0,2019/11/21,2019/11/21,.,4.0,I,NaN,NaN,NaN,NaN
3,2017/9/16,12755.0,M,2017/9/21,2017/9/21,0,0,0,0,0,...,1.0,2017/9/18,2017/9/18,.,3.0,I,NaN,NaN,NaN,NaN
4,2017/10/5,44.0,M,2017/10/10,2017/10/10,0,0,0,0,0,...,1.0,2017/10/5,2017/10/6,.,4.0,I,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,2023/2/27,NaN,M,2023/3/3,NaN,0,1,0,0,0,...,NaN,2023/2/26,2023/3/1,NaN,2.0,I,NaN,0.0,0.0,NaN
520,2023/3/1,NaN,M,2023/3/6,NaN,0,0,0,0,0,...,NaN,2023/3/1,2023/3/2,NaN,4.0,I,NaN,0.0,0.0,NaN
521,2023/2/21,NaN,M,2023/2/27,NaN,0,0,0,0,0,...,NaN,2023/2/21,2023/2/22,NaN,7.0,II,NaN,0.0,1.0,NaN
522,2023/2/28,NaN,M,2023/3/7,NaN,0,1,0,0,0,...,NaN,2023/2/28,2023/3/2,NaN,5.0,I,NaN,0.0,1.0,NaN
523,2023/3/7,NaN,F,2023/3/13,NaN,0,0,0,0,0,...,NaN,2023/3/7,2023/3/9,NaN,NaN,I,3.0,0.0,0.0,NaN

success

In [46]:
new_id_list = []
for i in range(raw_data.shape[0]):
    id_number = f"MACE{i+1:03d}" # 格式化ID為MACE001, MACE002, ..., MACE999
    new_id_list.append(id_number)

In [47]:
new_id_df = pd.DataFrame(new_id_list, columns=['Transformation_ID'])
raw_id_df = pd.DataFrame(raw_data.iloc[:, 0].values, columns=['Original_ID'])
corr_id_df = pd.concat([raw_id_df, new_id_df], axis=1)
corr_id_df.to_csv(save_data_path + "MACE_id_correlation.csv", index=False)
display(corr_id_df)
print("success")

      Original_ID Transformation_ID
0    414490914181           MACE001
1    534491345995           MACE002
2    584487583289           MACE003
3    354480714133           MACE004
4    364481044155           MACE005
..            ...               ...
519  334472223207           MACE520
520  474468168901           MACE521
521  484552428693           MACE522
522  454552424829           MACE523
523  374552404823           MACE524

[524 rows x 2 columns]

success

In [48]:
'''
這邊要再修改,因為Killip是羅馬數字,要轉成哪種型態,和VT的轉換
'''
new_data = pd.concat([new_id_df, non_research_id], axis=1)
new_data[['age']] = new_data[['age']].astype(int) # Raw data age有小數
display(new_data)
new_data.to_csv(save_data_path + "MACE_research_id_transformation.csv", index=False)
print('==================== success')

,Transformation_ID,indate_skna,ID,SEX,outdate_skna,INDEXDATE,acei_use,arb_use,c1_use,c3_use,...,master,PCIdate,SKNAdate1,mace_date2,TIMI,Killip,APACH II,ReMI,arrhythmia,p.s
0,MACE001,2016/12/12,13359.0,M,2016/12/16,2016/12/16,0,0,0,0,...,1.0,2016/12/12,2016/12/13,.,5.0,II,NaN,NaN,NaN,NaN
1,MACE002,2016/12/21,20198.0,M,2016/12/29,2016/12/29,1,0,0,0,...,1.0,2016/12/21,2016/12/22,.,4.0,III,NaN,NaN,NaN,NaN
2,MACE003,2019/11/18,11797.0,F,2019/11/25,2019/11/25,0,0,0,0,...,1.0,2019/11/21,2019/11/21,.,4.0,I,NaN,NaN,NaN,NaN
3,MACE004,2017/9/16,12755.0,M,2017/9/21,2017/9/21,0,0,0,0,...,1.0,2017/9/18,2017/9/18,.,3.0,I,NaN,NaN,NaN,NaN
4,MACE005,2017/10/5,44.0,M,2017/10/10,2017/10/10,0,0,0,0,...,1.0,2017/10/5,2017/10/6,.,4.0,I,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,MACE520,2023/2/27,NaN,M,2023/3/3,NaN,0,1,0,0,...,NaN,2023/2/26,2023/3/1,NaN,2.0,I,NaN,0.0,0.0,NaN
520,MACE521,2023/3/1,NaN,M,2023/3/6,NaN,0,0,0,0,...,NaN,2023/3/1,2023/3/2,NaN,4.0,I,NaN,0.0,0.0,NaN
521,MACE522,2023/2/21,NaN,M,2023/2/27,NaN,0,0,0,0,...,NaN,2023/2/21,2023/2/22,NaN,7.0,II,NaN,0.0,1.0,NaN
522,MACE523,2023/2/28,NaN,M,2023/3/7,NaN,0,1,0,0,...,NaN,2023/2/28,2023/3/2,NaN,5.0,I,NaN,0.0,1.0,NaN
523,MACE524,2023/3/7,NaN,F,2023/3/13,NaN,0,0,0,0,...,NaN,2023/3/7,2023/3/9,NaN,NaN,I,3.0,0.0,0.0,NaN

==================== success