In [2]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import joblib

In [ ]:
read_data_path = r"V:\dunwei\MACE\dataset\pre_process/"
save_data_path = r"V:\dunwei\MACE\dataset\pre_process/"
save_scaler_path = r"V:\dunwei\MACE\program\preprocessing\scaler/"

In [3]:
feature = ['acei_use', 'arb_use', 'c1_use', 'c3_use', 'alpha_use', 'coag_use', 'plt_use', 'NSTEMI', 'STEMI',
           'age', 'male', 'bmi', 'count_dys', 'count_dm','count_htn', 'count_a_ar', 'count_v_ar', 'count_copd',
           'count_asthma','cancer', 'smoke_try', 'Alcohol_try', 'BetelNut_try', 'bb_prior','bb_during', 'bb_after',
           'statin_use','SBP_1', 'DBP_1', 'HR_1','count_HF', 'NA1b', 'NA2b', 'NA1s', 'NA2s',
           'NA1r', 'NA2r', 'TIMI']

numerical_feature = ['age', 'bmi', 'SBP_1','DBP_1', 'HR_1', 'NA1b', 'NA2b',
                    'NA1s', 'NA2s', 'NA1r', 'NA2r', 'TIMI']

category_feature = ['acei_use', 'arb_use', 'c1_use', 'c3_use', 'alpha_use', 'coag_use', 'plt_use', 'NSTEMI', 'STEMI',
                    'count_dys', 'count_dm', 'count_htn', 'count_a_ar', 'count_v_ar', 'count_copd', 'count_asthma',
                    'cancer', 'bb_prior', 'bb_during','bb_after', 'statin_use', 'count_HF']

encoding_feature = ['male', 'smoke_try', 'Alcohol_try', 'BetelNut_try']

research_id = ['Transformation_ID']

label = ['mace']

In [4]:
raw_data = pd.read_csv(read_data_path + "MACE_research_id_transformation.csv")
display(raw_data)

,Transformation_ID,Unnamed: 1,indate_skna,Unnamed: 3,SEX,outdate_skna,INDEXDATE,acei_use,arb_use,c1_use,...,NA2r,master,PCIdate,SKNAdate1,mace_date2,TIMI,Killip,APACH II,ReMI,arrhythmia
0,MACE001,NaN,2016/12/12,NaN,M,2016/12/16,2016/12/16,0,0,0,...,1.359674,1.0,2016/12/12,2016/12/13,.,5.0,II,NaN,NaN,NaN
1,MACE002,NaN,2016/12/21,NaN,M,2016/12/29,2016/12/29,1,0,0,...,0.900024,1.0,2016/12/21,2016/12/22,.,4.0,III,NaN,NaN,NaN
2,MACE003,NaN,2019/11/18,NaN,F,2019/11/25,2019/11/25,0,0,0,...,NaN,1.0,2019/11/21,2019/11/21,.,4.0,I,NaN,NaN,NaN
3,MACE004,NaN,2017/9/16,NaN,M,2017/9/21,2017/9/21,0,0,0,...,2.074904,1.0,2017/9/18,2017/9/18,.,3.0,I,NaN,NaN,NaN
4,MACE005,NaN,2017/10/5,NaN,M,2017/10/10,2017/10/10,0,0,0,...,0.843889,1.0,2017/10/5,2017/10/6,.,4.0,I,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,MACE520,NaN,2023/2/27,NaN,M,2023/3/3,NaN,0,1,0,...,NaN,NaN,2023/2/26,2023/3/1,NaN,2.0,I,NaN,0.0,0.0
520,MACE521,NaN,2023/3/1,NaN,M,2023/3/6,NaN,0,0,0,...,NaN,NaN,2023/3/1,2023/3/2,NaN,4.0,I,NaN,0.0,0.0
521,MACE522,NaN,2023/2/21,NaN,M,2023/2/27,NaN,0,0,0,...,NaN,NaN,2023/2/21,2023/2/22,NaN,7.0,II,NaN,0.0,1.0
522,MACE523,NaN,2023/2/28,NaN,M,2023/3/7,NaN,0,1,0,...,NaN,NaN,2023/2/28,2023/3/2,NaN,5.0,I,NaN,0.0,1.0
523,MACE524,NaN,2023/3/7,NaN,F,2023/3/13,NaN,0,0,0,...,NaN,NaN,2023/3/7,2023/3/9,NaN,NaN,NaN,NaN,0.0,0.0

In [5]:
raw_data = raw_data[research_id + feature + label]
raw_data.to_csv(save_data_path + "MACE_raw_data.csv", index=False)
display(raw_data)

,Transformation_ID,acei_use,arb_use,c1_use,c3_use,alpha_use,coag_use,plt_use,NSTEMI,STEMI,...,HR_1,count_HF,NA1b,NA2b,NA1s,NA2s,NA1r,NA2r,TIMI,mace
0,MACE001,0,0,0,0,0,0,0,0.0,1,...,99.0,0.0,0.945758,1.914487,1.023857,1.788330,0.818643,1.359674,5.0,0
1,MACE002,1,0,0,0,0,0,1,1.0,0,...,72.0,0.0,0.866184,0.841020,1.057619,0.969397,1.085651,0.900024,4.0,0
2,MACE003,0,0,0,0,0,0,0,1.0,0,...,80.0,0.0,NaN,0.787275,NaN,NaN,NaN,NaN,4.0,0
3,MACE004,0,0,0,0,0,0,1,1.0,0,...,86.0,0.0,0.800577,1.162385,1.252417,2.451672,0.971383,2.074904,3.0,0
4,MACE005,0,0,0,0,0,0,0,0.0,1,...,64.0,0.0,0.915233,1.028591,1.204876,1.537874,1.025937,0.843889,4.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,MACE520,0,1,0,0,0,0,0,0.0,1,...,71.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0
520,MACE521,0,0,0,0,0,0,0,0.0,1,...,89.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,0
521,MACE522,0,0,0,0,0,0,0,0.0,1,...,74.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,7.0,0
522,MACE523,0,1,0,0,0,0,0,0.0,1,...,77.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0,0
523,MACE524,0,0,0,0,0,0,0,0.0,1,...,68.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [7]:
train_df = raw_data[~raw_data.isna().any(axis=1)].reset_index(drop=True) # 留下沒有缺失值得當作train
display(train_df)
test_df = raw_data[raw_data.isna().any(axis=1)].reset_index(drop=True)   # 留下有缺失值得當作test
display(test_df)
mask = test_df.isna().astype(int) # 可以將missing value補為1，記錄缺失值位置
display(mask)
train_df.to_csv(save_data_path + "MACE_raw_train.csv", index=False)
test_df.to_csv(save_data_path + "MACE_raw_test.csv", index=False)

,Transformation_ID,acei_use,arb_use,c1_use,c3_use,alpha_use,coag_use,plt_use,NSTEMI,STEMI,...,HR_1,count_HF,NA1b,NA2b,NA1s,NA2s,NA1r,NA2r,TIMI,mace
0,MACE001,0,0,0,0,0,0,0,0.0,1,...,99.0,0.0,0.945758,1.914487,1.023857,1.788330,0.818643,1.359674,5.0,0
1,MACE002,1,0,0,0,0,0,1,1.0,0,...,72.0,0.0,0.866184,0.841020,1.057619,0.969397,1.085651,0.900024,4.0,0
2,MACE004,0,0,0,0,0,0,1,1.0,0,...,86.0,0.0,0.800577,1.162385,1.252417,2.451672,0.971383,2.074904,3.0,0
3,MACE005,0,0,0,0,0,0,0,0.0,1,...,64.0,0.0,0.915233,1.028591,1.204876,1.537874,1.025937,0.843889,4.0,0
4,MACE006,0,1,0,0,0,0,0,0.0,1,...,53.0,0.0,0.795437,0.558267,1.008234,0.837322,0.835240,0.643852,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,MACE509,0,0,0,0,0,0,0,0.0,1,...,90.0,0.0,0.801832,0.685424,0.801207,1.064876,0.725261,1.578248,0.0,0
419,MACE510,0,0,0,0,0,0,0,0.0,1,...,67.0,1.0,1.230557,1.238073,1.193068,0.736866,1.040341,0.619125,5.0,0
420,MACE511,0,0,0,0,0,0,0,0.0,1,...,81.0,0.0,1.022384,0.623546,1.484015,0.834085,0.996738,1.046661,2.0,0
421,MACE512,0,0,0,0,0,0,0,0.0,1,...,80.0,0.0,0.968813,0.681255,2.033900,0.787138,1.256999,0.867778,5.0,0
422,MACE513,0,0,0,0,0,0,0,0.0,1,...,65.0,0.0,0.956282,0.639168,0.978639,0.587997,0.828895,0.529711,3.0,1

,Transformation_ID,acei_use,arb_use,c1_use,c3_use,alpha_use,coag_use,plt_use,NSTEMI,STEMI,...,HR_1,count_HF,NA1b,NA2b,NA1s,NA2s,NA1r,NA2r,TIMI,mace
0,MACE003,0,0,0,0,0,0,0,1.0,0,...,80.0,0.0,NaN,0.787275,NaN,NaN,NaN,NaN,4.0,0
1,MACE012,0,1,0,0,0,0,1,1.0,0,...,70.0,0.0,0.995880,0.997861,NaN,NaN,1.016893,0.964696,4.0,0
2,MACE018,0,0,0,0,1,0,0,1.0,0,...,76.0,0.0,1.506108,0.704344,NaN,NaN,NaN,NaN,3.0,0
3,MACE019,0,0,0,0,0,0,0,1.0,0,...,82.0,0.0,0.899679,0.648429,1.111143,0.528715,NaN,NaN,2.0,0
4,MACE020,0,0,0,0,0,0,0,0.0,1,...,72.0,0.0,1.080598,0.901802,NaN,NaN,1.231277,1.199658,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,MACE520,0,1,0,0,0,0,0,0.0,1,...,71.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0
97,MACE521,0,0,0,0,0,0,0,0.0,1,...,89.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,0
98,MACE522,0,0,0,0,0,0,0,0.0,1,...,74.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,7.0,0
99,MACE523,0,1,0,0,0,0,0,0.0,1,...,77.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0,0
100,MACE524,0,0,0,0,0,0,0,0.0,1,...,68.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

,Transformation_ID,acei_use,arb_use,c1_use,c3_use,alpha_use,coag_use,plt_use,NSTEMI,STEMI,...,HR_1,count_HF,NA1b,NA2b,NA1s,NA2s,NA1r,NA2r,TIMI,mace
0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,1,1,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,1,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,1,1,1,0,0
97,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,1,1,1,0,0
98,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,1,1,1,0,0
99,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,1,1,1,0,0
100,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,1,1,1,1,0

In [ ]:
re_order_raw_data = pd.concat([train_df, test_df], axis=0).reset_index(drop=True) # Test data 加在 Train data 後面
display(re_order_raw_data)
re_order_raw_data.to_csv(save_data_path + "MACE_re_order_raw_data.csv", index=False)

,Transformation_ID,acei_use,arb_use,c1_use,c3_use,alpha_use,coag_use,plt_use,NSTEMI,STEMI,...,HR_1,count_HF,NA1b,NA2b,NA1s,NA2s,NA1r,NA2r,TIMI,mace
0,MACE001,0,0,0,0,0,0,0,0.0,1,...,99.0,0.0,0.945758,1.914487,1.023857,1.788330,0.818643,1.359674,5.0,0
1,MACE002,1,0,0,0,0,0,1,1.0,0,...,72.0,0.0,0.866184,0.841020,1.057619,0.969397,1.085651,0.900024,4.0,0
2,MACE004,0,0,0,0,0,0,1,1.0,0,...,86.0,0.0,0.800577,1.162385,1.252417,2.451672,0.971383,2.074904,3.0,0
3,MACE005,0,0,0,0,0,0,0,0.0,1,...,64.0,0.0,0.915233,1.028591,1.204876,1.537874,1.025937,0.843889,4.0,0
4,MACE006,0,1,0,0,0,0,0,0.0,1,...,53.0,0.0,0.795437,0.558267,1.008234,0.837322,0.835240,0.643852,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,MACE520,0,1,0,0,0,0,0,0.0,1,...,71.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0
520,MACE521,0,0,0,0,0,0,0,0.0,1,...,89.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,0
521,MACE522,0,0,0,0,0,0,0,0.0,1,...,74.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,7.0,0
522,MACE523,0,1,0,0,0,0,0,0.0,1,...,77.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0,0
523,MACE524,0,0,0,0,0,0,0,0.0,1,...,68.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [24]:
numerical_features = re_order_raw_data[numerical_feature]
display(numerical_features)
categorical_features = re_order_raw_data[category_feature]
display(categorical_features)
encoding_features = re_order_raw_data[encoding_feature]
display(encoding_features)

,age,bmi,SBP_1,DBP_1,HR_1,NA1b,NA2b,NA1s,NA2s,NA1r,NA2r,TIMI
0,43,25.796010,153.0,106.0,99.0,0.945758,1.914487,1.023857,1.788330,0.818643,1.359674,5.0
1,67,21.039557,118.0,64.0,72.0,0.866184,0.841020,1.057619,0.969397,1.085651,0.900024,4.0
2,66,27.390919,150.0,78.0,86.0,0.800577,1.162385,1.252417,2.451672,0.971383,2.074904,3.0
3,69,27.548209,181.0,103.0,64.0,0.915233,1.028591,1.204876,1.537874,1.025937,0.843889,4.0
4,61,26.609713,143.0,91.0,53.0,0.795437,0.558267,1.008234,0.837322,0.835240,0.643852,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
519,45,25.700000,128.0,81.0,71.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0
520,83,25.100000,133.0,95.0,89.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0
521,66,23.500000,112.0,66.0,74.0,NaN,NaN,NaN,NaN,NaN,NaN,7.0
522,72,23.900000,146.0,79.0,77.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0
523,59,23.100000,156.0,87.0,68.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,acei_use,arb_use,c1_use,c3_use,alpha_use,coag_use,plt_use,NSTEMI,STEMI,count_dys,...,count_a_ar,count_v_ar,count_copd,count_asthma,cancer,bb_prior,bb_during,bb_after,statin_use,count_HF
0,0,0,0,0,0,0,0,0.0,1,1.0,...,0.0,0.0,0.0,0.0,0,0,1,1,0,0.0
1,1,0,0,0,0,0,1,1.0,0,0.0,...,0.0,0.0,0.0,0.0,0,1,1,1,0,0.0
2,0,0,0,0,0,0,1,1.0,0,0.0,...,0.0,0.0,0.0,0.0,0,0,1,1,0,0.0
3,0,0,0,0,0,0,0,0.0,1,0.0,...,0.0,0.0,0.0,0.0,0,0,1,1,0,0.0
4,0,1,0,0,0,0,0,0.0,1,0.0,...,0.0,0.0,0.0,0.0,0,0,1,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,0,1,0,0,0,0,0,0.0,1,0.0,...,0.0,0.0,0.0,0.0,0,1,1,1,0,0.0
520,0,0,0,0,0,0,0,0.0,1,0.0,...,0.0,0.0,0.0,0.0,0,0,1,1,0,0.0
521,0,0,0,0,0,0,0,0.0,1,0.0,...,1.0,0.0,0.0,0.0,0,0,1,1,0,0.0
522,0,1,0,0,0,0,0,0.0,1,0.0,...,1.0,0.0,0.0,0.0,0,1,1,1,0,0.0
523,0,0,0,0,0,0,0,0.0,1,0.0,...,0.0,0.0,0.0,0.0,0,0,1,1,0,0.0

     male  smoke_try  Alcohol_try  BetelNut_try
0       1        1.0            1           0.0
1       1        1.0            0           0.0
2       1        0.0            0           0.0
3       1        1.0            0           0.0
4       1        1.0            0           0.0
..    ...        ...          ...           ...
519     1        1.0            0           0.0
520     1        0.0            0           0.0
521     1        1.0            0           0.0
522     1        0.0            0           0.0
523     0        0.0            0           0.0

[524 rows x 4 columns]

In [25]:
numerical_placeholder = numerical_features.fillna(numerical_features.mean()) # 使用平均值填補數值型特徵的缺失值
display(numerical_placeholder)
categorical_placeholder = categorical_features.apply(lambda x: x.fillna(x.mode()[0]), axis = 0) # 使用眾數填補類別型特徵的缺失值
display(categorical_placeholder)
encoding_placeholder = encoding_features.apply(lambda x: x.fillna(x.mode()[0]), axis = 0) # 使用眾數填補編碼型特徵的缺失值
display(encoding_placeholder)

,age,bmi,SBP_1,DBP_1,HR_1,NA1b,NA2b,NA1s,NA2s,NA1r,NA2r,TIMI
0,43,25.796010,153.0,106.0,99.0,0.945758,1.914487,1.023857,1.788330,0.818643,1.359674,5.000000
1,67,21.039557,118.0,64.0,72.0,0.866184,0.841020,1.057619,0.969397,1.085651,0.900024,4.000000
2,66,27.390919,150.0,78.0,86.0,0.800577,1.162385,1.252417,2.451672,0.971383,2.074904,3.000000
3,69,27.548209,181.0,103.0,64.0,0.915233,1.028591,1.204876,1.537874,1.025937,0.843889,4.000000
4,61,26.609713,143.0,91.0,53.0,0.795437,0.558267,1.008234,0.837322,0.835240,0.643852,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
519,45,25.700000,128.0,81.0,71.0,1.127263,1.658339,1.264307,1.796950,1.159151,2.411121,2.000000
520,83,25.100000,133.0,95.0,89.0,1.127263,1.658339,1.264307,1.796950,1.159151,2.411121,4.000000
521,66,23.500000,112.0,66.0,74.0,1.127263,1.658339,1.264307,1.796950,1.159151,2.411121,7.000000
522,72,23.900000,146.0,79.0,77.0,1.127263,1.658339,1.264307,1.796950,1.159151,2.411121,5.000000
523,59,23.100000,156.0,87.0,68.0,1.127263,1.658339,1.264307,1.796950,1.159151,2.411121,3.566929

,acei_use,arb_use,c1_use,c3_use,alpha_use,coag_use,plt_use,NSTEMI,STEMI,count_dys,...,count_a_ar,count_v_ar,count_copd,count_asthma,cancer,bb_prior,bb_during,bb_after,statin_use,count_HF
0,0,0,0,0,0,0,0,0.0,1,1.0,...,0.0,0.0,0.0,0.0,0,0,1,1,0,0.0
1,1,0,0,0,0,0,1,1.0,0,0.0,...,0.0,0.0,0.0,0.0,0,1,1,1,0,0.0
2,0,0,0,0,0,0,1,1.0,0,0.0,...,0.0,0.0,0.0,0.0,0,0,1,1,0,0.0
3,0,0,0,0,0,0,0,0.0,1,0.0,...,0.0,0.0,0.0,0.0,0,0,1,1,0,0.0
4,0,1,0,0,0,0,0,0.0,1,0.0,...,0.0,0.0,0.0,0.0,0,0,1,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,0,1,0,0,0,0,0,0.0,1,0.0,...,0.0,0.0,0.0,0.0,0,1,1,1,0,0.0
520,0,0,0,0,0,0,0,0.0,1,0.0,...,0.0,0.0,0.0,0.0,0,0,1,1,0,0.0
521,0,0,0,0,0,0,0,0.0,1,0.0,...,1.0,0.0,0.0,0.0,0,0,1,1,0,0.0
522,0,1,0,0,0,0,0,0.0,1,0.0,...,1.0,0.0,0.0,0.0,0,1,1,1,0,0.0
523,0,0,0,0,0,0,0,0.0,1,0.0,...,0.0,0.0,0.0,0.0,0,0,1,1,0,0.0

     male  smoke_try  Alcohol_try  BetelNut_try
0       1        1.0            1           0.0
1       1        1.0            0           0.0
2       1        0.0            0           0.0
3       1        1.0            0           0.0
4       1        1.0            0           0.0
..    ...        ...          ...           ...
519     1        1.0            0           0.0
520     1        0.0            0           0.0
521     1        1.0            0           0.0
522     1        0.0            0           0.0
523     0        0.0            0           0.0

[524 rows x 4 columns]

In [ ]:
scaler = MinMaxScaler()
scaler = scaler.fit(numerical_placeholder) # 生成min(x)和max(x)，做 Normalization
numerical_std = scaler.transform(numerical_placeholder)
numerical_std_df = pd.DataFrame(numerical_std, columns=numerical_feature)
display(numerical_std_df)
save_scaler = joblib.dump(scaler, save_scaler_path + "MACE_scaler.joblib") # 再轉回去
print(f'MACE_scaler saved to {save_scaler[0]}')

,age,bmi,SBP_1,DBP_1,HR_1,NA1b,NA2b,NA1s,NA2s,NA1r,NA2r,TIMI
0,0.265625,0.395458,0.539604,0.509434,0.673469,0.022758,0.026093,0.025255,0.022283,0.016461,0.002634,0.454545
1,0.640625,0.221229,0.366337,0.245283,0.489796,0.018967,0.007576,0.026782,0.009134,0.028257,0.001401,0.363636
2,0.625000,0.453880,0.524752,0.333333,0.585034,0.015843,0.013119,0.035592,0.032934,0.023209,0.004552,0.272727
3,0.671875,0.459641,0.678218,0.490566,0.435374,0.021304,0.010811,0.033442,0.018262,0.025619,0.001251,0.363636
4,0.546875,0.425264,0.490099,0.415094,0.360544,0.015598,0.002698,0.024548,0.007013,0.017195,0.000714,0.090909
...,...,...,...,...,...,...,...,...,...,...,...,...
519,0.296875,0.391941,0.415842,0.352201,0.482993,0.031403,0.021674,0.036129,0.022422,0.031503,0.005453,0.181818
520,0.890625,0.369963,0.440594,0.440252,0.605442,0.031403,0.021674,0.036129,0.022422,0.031503,0.005453,0.363636
521,0.625000,0.311355,0.336634,0.257862,0.503401,0.031403,0.021674,0.036129,0.022422,0.031503,0.005453,0.636364
522,0.718750,0.326007,0.504950,0.339623,0.523810,0.031403,0.021674,0.036129,0.022422,0.031503,0.005453,0.454545
523,0.515625,0.296703,0.554455,0.389937,0.462585,0.031403,0.021674,0.036129,0.022422,0.031503,0.005453,0.324266

MACE_scaler saved to V:\dunwei\MACE\program\preprocessing\scaler/MACE_scaler.joblib

In [27]:
encoded_features = pd.get_dummies(encoding_placeholder, columns=encoding_feature, dtype=int) # get_dummies轉成one-hot encoding method
display(encoded_features)

,male_0,male_1,smoke_try_0.0,smoke_try_1.0,smoke_try_2.0,Alcohol_try_0,Alcohol_try_1,Alcohol_try_2,BetelNut_try_0.0,BetelNut_try_1.0,BetelNut_try_2.0
0,0,1,0,1,0,0,1,0,1,0,0
1,0,1,0,1,0,1,0,0,1,0,0
2,0,1,1,0,0,1,0,0,1,0,0
3,0,1,0,1,0,1,0,0,1,0,0
4,0,1,0,1,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
519,0,1,0,1,0,1,0,0,1,0,0
520,0,1,1,0,0,1,0,0,1,0,0
521,0,1,0,1,0,1,0,0,1,0,0
522,0,1,1,0,0,1,0,0,1,0,0
523,1,0,1,0,0,1,0,0,1,0,0

In [28]:
std_encoding_data = pd.concat([re_order_raw_data[research_id], numerical_std_df, categorical_placeholder,
                               encoded_features, re_order_raw_data[label]], axis=1)
display(std_encoding_data)

,Transformation_ID,age,bmi,SBP_1,DBP_1,HR_1,NA1b,NA2b,NA1s,NA2s,...,smoke_try_0.0,smoke_try_1.0,smoke_try_2.0,Alcohol_try_0,Alcohol_try_1,Alcohol_try_2,BetelNut_try_0.0,BetelNut_try_1.0,BetelNut_try_2.0,mace
0,MACE001,0.265625,0.395458,0.539604,0.509434,0.673469,0.022758,0.026093,0.025255,0.022283,...,0,1,0,0,1,0,1,0,0,0
1,MACE002,0.640625,0.221229,0.366337,0.245283,0.489796,0.018967,0.007576,0.026782,0.009134,...,0,1,0,1,0,0,1,0,0,0
2,MACE004,0.625000,0.453880,0.524752,0.333333,0.585034,0.015843,0.013119,0.035592,0.032934,...,1,0,0,1,0,0,1,0,0,0
3,MACE005,0.671875,0.459641,0.678218,0.490566,0.435374,0.021304,0.010811,0.033442,0.018262,...,0,1,0,1,0,0,1,0,0,0
4,MACE006,0.546875,0.425264,0.490099,0.415094,0.360544,0.015598,0.002698,0.024548,0.007013,...,0,1,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,MACE520,0.296875,0.391941,0.415842,0.352201,0.482993,0.031403,0.021674,0.036129,0.022422,...,0,1,0,1,0,0,1,0,0,0
520,MACE521,0.890625,0.369963,0.440594,0.440252,0.605442,0.031403,0.021674,0.036129,0.022422,...,1,0,0,1,0,0,1,0,0,0
521,MACE522,0.625000,0.311355,0.336634,0.257862,0.503401,0.031403,0.021674,0.036129,0.022422,...,0,1,0,1,0,0,1,0,0,0
522,MACE523,0.718750,0.326007,0.504950,0.339623,0.523810,0.031403,0.021674,0.036129,0.022422,...,1,0,0,1,0,0,1,0,0,0
523,MACE524,0.515625,0.296703,0.554455,0.389937,0.462585,0.031403,0.021674,0.036129,0.022422,...,1,0,0,1,0,0,1,0,0,0

In [29]:
train_num = train_df.shape[0]
print(train_num)
train_std_encoding = std_encoding_data.iloc[:train_num, :]
display(train_std_encoding)
test_std_encoding = std_encoding_data.iloc[train_num:, :]
display(test_std_encoding)

423

,Transformation_ID,age,bmi,SBP_1,DBP_1,HR_1,NA1b,NA2b,NA1s,NA2s,...,smoke_try_0.0,smoke_try_1.0,smoke_try_2.0,Alcohol_try_0,Alcohol_try_1,Alcohol_try_2,BetelNut_try_0.0,BetelNut_try_1.0,BetelNut_try_2.0,mace
0,MACE001,0.265625,0.395458,0.539604,0.509434,0.673469,0.022758,0.026093,0.025255,0.022283,...,0,1,0,0,1,0,1,0,0,0
1,MACE002,0.640625,0.221229,0.366337,0.245283,0.489796,0.018967,0.007576,0.026782,0.009134,...,0,1,0,1,0,0,1,0,0,0
2,MACE004,0.625000,0.453880,0.524752,0.333333,0.585034,0.015843,0.013119,0.035592,0.032934,...,1,0,0,1,0,0,1,0,0,0
3,MACE005,0.671875,0.459641,0.678218,0.490566,0.435374,0.021304,0.010811,0.033442,0.018262,...,0,1,0,1,0,0,1,0,0,0
4,MACE006,0.546875,0.425264,0.490099,0.415094,0.360544,0.015598,0.002698,0.024548,0.007013,...,0,1,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,MACE509,0.546875,0.406593,0.440594,0.477987,0.612245,0.015902,0.004892,0.015185,0.010667,...,0,0,1,1,0,0,1,0,0,0
419,MACE510,0.375000,0.509158,0.698020,0.591195,0.455782,0.036323,0.014425,0.032908,0.005400,...,1,0,0,1,0,0,1,0,0,0
420,MACE511,0.234375,0.472527,0.653465,0.553459,0.551020,0.026407,0.003824,0.046066,0.006961,...,0,1,0,1,0,0,1,0,0,0
421,MACE512,0.546875,0.260073,0.440594,0.522013,0.544218,0.023856,0.004820,0.070935,0.006207,...,0,1,0,1,0,0,1,0,0,0
422,MACE513,0.593750,0.571429,0.410891,0.333333,0.442177,0.023259,0.004094,0.023210,0.003010,...,1,0,0,0,1,0,1,0,0,1

,Transformation_ID,age,bmi,SBP_1,DBP_1,HR_1,NA1b,NA2b,NA1s,NA2s,...,smoke_try_0.0,smoke_try_1.0,smoke_try_2.0,Alcohol_try_0,Alcohol_try_1,Alcohol_try_2,BetelNut_try_0.0,BetelNut_try_1.0,BetelNut_try_2.0,mace
423,MACE003,0.625000,0.354090,0.663366,0.440252,0.544218,0.031403,0.006649,0.036129,0.022422,...,1,0,0,1,0,0,1,0,0,0
424,MACE012,0.671875,0.795559,0.500000,0.408805,0.476190,0.025145,0.010281,0.036129,0.022422,...,1,0,0,1,0,0,1,0,0,0
425,MACE018,0.468750,0.439180,0.549505,0.465409,0.517007,0.049448,0.005218,0.036129,0.022422,...,0,1,0,0,1,0,0,1,0,0
426,MACE019,0.328125,0.309898,0.633663,0.490566,0.557823,0.020563,0.004253,0.029202,0.002058,...,0,1,0,1,0,0,1,0,0,0
427,MACE020,0.609375,0.431677,0.415842,0.339623,0.489796,0.029180,0.008624,0.036129,0.022422,...,1,0,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,MACE520,0.296875,0.391941,0.415842,0.352201,0.482993,0.031403,0.021674,0.036129,0.022422,...,0,1,0,1,0,0,1,0,0,0
520,MACE521,0.890625,0.369963,0.440594,0.440252,0.605442,0.031403,0.021674,0.036129,0.022422,...,1,0,0,1,0,0,1,0,0,0
521,MACE522,0.625000,0.311355,0.336634,0.257862,0.503401,0.031403,0.021674,0.036129,0.022422,...,0,1,0,1,0,0,1,0,0,0
522,MACE523,0.718750,0.326007,0.504950,0.339623,0.523810,0.031403,0.021674,0.036129,0.022422,...,1,0,0,1,0,0,1,0,0,0
523,MACE524,0.515625,0.296703,0.554455,0.389937,0.462585,0.031403,0.021674,0.036129,0.022422,...,1,0,0,1,0,0,1,0,0,0

In [ ]:
std_encoding_data.to_csv(save_data_path + "MACE_std_encoding.csv", index=False)
print(f'std_encoding_data saved to {save_data_path  + "MACE_std_encoding.csv"}')
train_std_encoding.to_csv(save_data_path + "MACE_std_encoding_train.csv", index=False)
print(f'train_std_encoding saved to {save_data_path + "MACE_std_encoding_train.csv"}')
test_std_encoding.to_csv(save_data_path + "MACE_std_encoding_test.csv", index=False)
print(f'test_std_encoding saved to {save_data_path + "MACE_std_encoding_test.csv"}')
mask.to_csv(save_data_path + "MACE_mask.csv", index=False)
print(f'mask saved to {save_data_path + "MACE_mask.csv"}')

std_encoding_data saved to V:\dunwei\MACE\dataset\pre_process/MACE_std_encoding.csv
train_std_encoding saved to V:\dunwei\MACE\dataset\pre_process/MACE_std_encoding_train.csv
test_std_encoding saved to V:\dunwei\MACE\dataset\pre_process/MACE_std_encoding_test.csv
mask saved to V:\dunwei\MACE\dataset\pre_process/MACE_mask.csv